// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollectMetrics() {
  return window['go']['main']['App']['CollectMetrics']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}
