// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollectMetrics() {
  return window['go']['main']['App']['CollectMetrics']();
}

export function ExpandToDashboard() {
  return window['go']['main']['App']['ExpandToDashboard']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function ShrinkToWidget() {
  return window['go']['main']['App']['ShrinkToWidget']();
}
